# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dac8e3ab316e681fb762f28999a0d54d2a68c27ed9f72dcf500daaf53af2f1238aa0958c60069ab57fad7327c7eea5fdfdb3f482fa6ad5bd80d28b5535e7eda7

test:
  secret_key_base: 47e5afff4600b14a2ffca1f230a4240ec7c35d82ccfe976124991f5365182ae9a6783c8e812d46371de4069c336c27b0851196f08f4ab6404c5a41c02229d848

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
